// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bararmcpxiqfriwiwrwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcmFybWNweGlxZnJpd2l3cndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjY2MjAsImV4cCI6MjA2ODM0MjYyMH0.ttBbmDfIIzZm_84GEaIg3ZHos3A7v_q8lvw51O8Z0S4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});